---
# Maven

- name: Download Apache Maven 
  get_url: url=http://www.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz dest=/tmp/apache-maven-3.3.9-bin.tar.gz

- name: Untar Maven 
  become: yes
  shell: chdir=/tmp creates=/opt/apache-maven-3.3.9 tar -zxf apache-maven-3.3.9-bin.tar.gz -C /opt
 