---
intellij_build: "IU-173.3942.27%"
intellij_local_package_location: "/tmp/ideaIU-2017.3.1-no-jdk.tar.gz"
intellij_include_jdk: False
intellij_install_dir: "/opt/intellij"
intellij_version: "2017.3.1"
intellij_url: "https://download.jetbrains.com/idea/ideaIU-2017.3.1-no-jdk.tar.gz"
